Ans 006 115 #150 #67
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #166
Opened 2024-03-14 15:44 UTC by TristanKEREVAL

2024-03-14 17:04 UTC, nriss requested changes
Je prends la suite demain

2024-03-14 17:04 UTC, nriss commented on input/fsh/input/fsh/invariants/regle-StatutUnite.fsh
> +Expression: "input.type.where(text='idUnite').exists() and input.type.where(text='nomUnite').exists() and input.type.where(text='categorieOrganisation').exists() and input.type.where(text='modePriseC
L'expression n'est pas correcte ici, il faut utiliser 'implies'. Cf l'exemple : https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/fsh/profiles/FrCorePatientINS.fsh

2024-03-14 17:04 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSBundleResultatRechercheDecisionEvaluation.fsh
> +* type = #searchset (exactly)
enlever (exactly) partout

2024-03-14 17:04 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSBundleResultatRechercheDecisionEvaluation.fsh
> +* ^version = "2.1"
supprimer ces métadonnées partout

2024-03-15 07:56 UTC, TristanKEREVAL commented on input/fsh/input/fsh/profiles/ESMSBundleResultatRechercheDecisionEvaluation.fsh
> +* ^version = "2.1"
OK

2024-03-15 07:57 UTC, TristanKEREVAL commented on input/fsh/input/fsh/profiles/ESMSBundleResultatRechercheDecisionEvaluation.fsh
> +* type = #searchset (exactly)
OK

2024-03-15 07:57 UTC, TristanKEREVAL commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[idNat_Struct].type.text = "idNat_Struct" (exactly)
OK

2024-03-15 07:57 UTC, TristanKEREVAL commented on input/fsh/input/fsh/instances/id-exemple-sdo-task-1-in-bundle.fsh
> +* id = "exemple1"
OK

2024-03-15 07:57 UTC, TristanKEREVAL commented on input/fsh/input/fsh/index.txt
> +Name                                                                               Type       File
OK

2024-03-15 08:17 UTC, nriss requested changes

2024-03-15 08:17 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.use 1..
Pas besoin de mettre 1.. si c'est fixé juste derrière

2024-03-15 08:17 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* identifier 2..
Les 2 identifier obligatoires ne sont pas précisés ?

2024-03-15 08:17 UTC, nriss commented on input/fsh/sushi-config.yaml
> +version: 4.0.2-ballot-2
@SEBELIN quelle version veux-tu pour la prochaine release ?

2024-03-15 08:23 UTC, jguihot commented
@TristanKEREVAL , pourras-tu lier cette PR aux issues appropriées, et ajouter en commentaire les évol effectuées ?

2024-03-15 09:52 UTC, TristanKEREVAL commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* identifier 2..
Ils sont précisés dans la SD SDODocumentRefernce qui sert de base value

2024-03-15 10:04 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* identifier 2..
Alors le mieux c'est de faire des slices au niveau de SDODocumentReference et de rendre les slices obligatoires ici

2024-03-15 12:13 UTC, TristanKEREVAL commented on input/fsh/input/fsh/aliases.fsh
> +Alias: $documentreference.html = https://hl7.org/fhir/R4/documentreference.html
ok

2024-03-15 14:50 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[nomESMS].type.text = "nomESMS" (exactly)
Préconisé dans une précédente release et tracé dans une issue GIT : https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/153
@SEBELIN , création d'un jeu de valeur pour discriminer les slices et éviter les champs textes, qu'en penses-tu ?

2024-03-15 14:58 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* identifier 2..
@TristanKEREVAL , je rejoins Nicolas, la ressource de base à modifier est la ressource mère SDODocumentReference. 
MAIS, @nriss , tu as de l'avance ! C'est effectivement une des évolutions mises en place par Tristan pour mieux gérer les règles de gestion. Mais nous avons souhaité distinguer les évol liées au passage à FSH de celles liées aux évolutions des règles de gestion et aux cardinalités. Ca arrive donc !

2024-03-15 15:05 UTC, jguihot commented on input/fsh/sushi-config.yaml
> +version: 4.0.2-ballot-2
@nriss , ça sera effectivement à discuter, mais, dans le cadre de nos prestations, les évolutions sont indépendantes des releases. La gestion des releases et publication reste à la main de @SEBELIN et se fera donc dans une PR distincte. Il était question d'une 4.0.2-ballot-3, mais c'était dans l'idée où il n'y aurait pas de mise en concertation sur l'espace de concertation avant la livraison des actuels travaux. La concertation étant lancée, je ne sais pas si c'est toujours d'actualité.

2024-03-19 07:53 UTC, SEBELIN commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[nomESMS].type.text = "nomESMS" (exactly)
on peut prendre cette option temporaire tant que la nomenclature n'est pas intégrée dans les NOS.

2024-03-19 07:59 UTC, SEBELIN commented on input/fsh/sushi-config.yaml
> +version: 4.0.2-ballot-2
la version correspond à 4.0.2-ballot-3
Retours de concertation IG 4.0.2-ballot-2 + passage en FSH : 4.0.2-ballot-3

2024-03-19 08:00 UTC, SEBELIN commented on input/fsh/sushi-config.yaml
> +version: 4.0.2-ballot-2
pour info la concertation 4.0.2-ballot-2 se termine le 22/03

2024-03-19 08:02 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[nomESMS].type.text = "nomESMS" (exactly)
@SEBELIN , elle n'aura pas vocation à être intégrée dans les NOS, du moins je ne pense pas. Il ne s'agit pas d'une nomenclature métier mais d'une nomenclature technique pour identifier les différentes occurences de nos input. Je résume bien @nriss ?

2024-03-19 08:05 UTC, SEBELIN commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[nomESMS].type.text = "nomESMS" (exactly)
puisque c'est purement technique Suivez les recommandations de Nicolas

2024-03-19 08:46 UTC, nriss commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* input[nomESMS].type.text = "nomESMS" (exactly)
Oui pas d'intérêt à l'intégrer dans les NOS à mon sens :)

2024-03-22 11:01 UTC, TristanKEREVAL commented
@nriss je ne comprends pas ton retour : 
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/4623f15a-20a6-421c-a1a3-155a326fa655)
Ma réponse ne semble pas s'envoyer je ne sais pas pourquoi.

Pourquoi faudrait il enlever la cardinalité ? Même si la ligne d'en dessous fixe un binding, on veut quand même la cardinalité obligatoire

2024-03-22 11:12 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.use 1..
Je viens de vérifier le comportement, mon commentaire est erroné : il faut forcer la cardinalité minimale, fixer la valeur n'est pas suffisante! Je clos le commentaire :)

2024-03-22 11:23 UTC, jguihot commented
@nriss , OK pour prise en compte des correctifs techniques. je vérifie le fonctionnel de mon coté

2024-03-22 12:33 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* ^version = "2.3"
Lignes ^ peuvent être supprimées

2024-03-22 12:34 UTC, nriss approved these changes
Super! Merci :)
Un petit commentaire restant

2024-03-22 15:24 UTC, jguihot approved these changes
quelques commentaires qui rejoignent en partie ceux de Nicolas. Ok pour moi pour le reste

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.use 1..
mznsur max = 1

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.value 1..
manque max =1 (1 seul identifier sur les 2 doit être référencé)

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* ^version = "1.2"
idem suppression des metadata

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* content.attachment.title ^short = "Titre identifiant le contenu du document transporté. Le titre doit être soit 'Document Individu et décision', soit 'Document évaluation'"
Je supprimerais le nom du titre en ajoutant plutôt la contrainte regle-NomPieceJointe directement sur cet élément. Présentement le nom apparaît dans la description de l'élément et dans la description de la règle = discordance possible. Peut être traité dans la 2e PR d'évolutions des SD

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDOBundleResultatRechercheNotificationESMS.fsh
> +* ^date = "2023-06-27T09:51:35+02:00"
idem suppression des metadata

2024-03-22 15:24 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDOTask.fsh
> +* ^status = #active
idem suppression des metadata

2024-03-22 16:09 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* category = $loinc#59284-0 "Consent"
Hello!
Très bonne question, sans solution satisfaisante apparente j'ai l'impression ...
Dans le cas présent, je propose effectivement d'enlever le display, étant donné qu'il s'agit du nom de la ressource (Consent), on ne perd rien à l'enlever à mon sens

Est-ce que ça vous convient ?

2024-03-22 16:12 UTC, nriss commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* category = $loinc#59284-0 "Consent"
Ok pour le laisser!

2024-03-22 16:37 UTC, jguihot commented
@TristanKEREVAL , autre remarque plus générique, je reverrais bien l'architecture des dossiers FSH pour séparer les exemples des Capability Statements et identifier clairement ces derniers comme tels dans un dossier CapabilityStatement (voir PDSm).
Question bonus : pourquoi préfixer les noms des exemples par "id-" ?

2024-03-22 17:47 UTC, jguihot requested changes
Corrections requises sur les CS

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/ESMSConsommateur.fsh
> +* format[+] = #application/fhir+rdf
format rdf utilisé ?

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/ESMSGestionnaire.fsh
Attention, @TristanKEREVAL , le système ici n'est pas spécifiquement un gestionnaire ESMS. Le nom de ce système est SdO. SdOGestionnaire est donc plus approprié.
Autre remarque, comme échangé ensemble (voir conversation du 26/02), il n'y a qu'un seul CS gestionnaire qui était à intégrer. Dans ce fichier je vois un merge des CS ESMS et SDO

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/MDPHConsommateur.fsh
Hors sujet. à garder pour être intégré lors de la mise en place du volet SI-SdO, Pas à afficher dans la version actuelle de l'IG

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/MDPHProducteur.fsh
Hors sujet. à garder pour être intégré lors de la mise en place du volet SI-SdO, Pas à afficher dans la version actuelle de l'IG

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-sdo-bundle-resultat-recherche-notifications-esms.fsh
> +Usage: #definition
Usage: #example

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-sdo-document-reference.fsh
> +Usage: #definition
Usage: #example

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-sdo-task.fsh
> +Usage: #definition
Usage: #example

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-esms-documentreference-1-in-bundle.fsh
possible de gérer les occurences dans un seul et unique fichier bundle ? A l'image de ce qui a été fait pour TDDUI ? Pour ne pas démultiplier les fichiers

2024-03-22 17:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-sdo-task-1-in-bundle.fsh
même remarque que pour les documentReference, possible de gérer ça dans un unique fichier ?

2024-03-25 08:07 UTC, TristanKEREVAL commented
> @TristanKEREVAL , autre remarque plus générique, je reverrais bien l'architecture des dossiers FSH pour séparer les exemples des Capability Statements et identifier clairement ces derniers comme tels dans un dossier CapabilityStatement (voir PDSm). Question bonus : pourquoi préfixer les noms des exemples par "id-" ?

Pour l'architecture ok ! Pour les exemples ça vient de la conversion JSON->FSH via GOFsh qui a automatiquement mit ça

2024-03-25 08:28 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.use 1..
Je clôture, max nativement à 1

2024-03-25 08:28 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSConsent.fsh
> +* provision.data.reference.identifier.value 1..
Je clôture, max nativement à 1

2024-03-25 08:34 UTC, TristanKEREVAL commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* content.attachment.title ^short = "Titre identifiant le contenu du document transporté. Le titre doit être soit 'Document Individu et décision', soit 'Document évaluation'"
Le mieux pour moi est la suppression du short pour ne garder que la règle de gestion, c'est ok @jguihot  ?

2024-03-25 08:34 UTC, TristanKEREVAL commented on input/fsh/input/fsh/instances/id-exemple-esms-documentreference-1-in-bundle.fsh
> possible de gérer les occurences dans un seul et unique fichier bundle ? A l'image de ce qui a été fait pour TDDUI ? Pour ne pas démultiplier les fichiers

Possible, c'est gofsh qui a fait ça comme ça et je trouvais ça pas mal de séparer les éléments présents dans le bundle, et le bundle en lui même. Ce que je peux faire pour garder cette structure c'est de tout définir dans un seul fichier sinon si ça vous va

2024-03-25 08:34 UTC, TristanKEREVAL commented on input/fsh/input/fsh/instances/id-exemple-sdo-task-1-in-bundle.fsh
> même remarque que pour les documentReference, possible de gérer ça dans un unique fichier ?

Voir réponse précédente

2024-03-25 08:47 UTC, jguihot commented on input/fsh/input/fsh/instances/id-exemple-esms-documentreference-1-in-bundle.fsh
C'est effectivement comme ça que c'est fait sur TDDUI. Toutes les occurrences sont bien séparées, mais tout est dans un seul et unique fichier. Je trouve la séparation des occurrences pertinentes et claires, en revanche, le fait qu'elles soient dans plusieurs fichiers rend moins facile la maintenance

2024-03-25 09:01 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* content.attachment.title ^short = "Titre identifiant le contenu du document transporté. Le titre doit être soit 'Document Individu et décision', soit 'Document évaluation'"
Alors, je n'irais pas jusqu'à supprimer le short, en revanche j'enlèverais effectivement la RG de la description. 
Nouveau short proposé : "Code permettant d'identifier si le document véhicule une décision ou une évaluation".
Et dans la mesure où la RG n'implique pas d'autres éléments de la ressource, il me paraît plus claire de la poser sur l'élément ciblé plutôt que sur la ressource. Non ?

2024-03-25 14:46 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
> +* content.attachment.title ^short = "Titre identifiant le contenu du document transporté. Le titre doit être soit 'Document Individu et décision', soit 'Document évaluation'"
Petit mix de commentaires, le premier portait sur le title, le second sur le type. Pour le title, conserver uniquement le short "Titre identifiant le contenu du document transporté"

2024-03-25 21:20 UTC, jguihot requested changes
Dernière correction à faire sur les CS et si OK pour toi @nriss , OK pour merge

2024-03-25 21:20 UTC, jguihot commented on input/fsh/input/fsh/CapabilityStatement/SDOGestionnaire.fsh
> +* rest.resource[=].profile = "https://interop.esante.gouv.fr/ig/fhir/sdo/StructureDefinition/sdo-document-reference"
mauvais documentReference conservé. sdo au lieu de esms

2024-03-25 21:20 UTC, jguihot commented on input/fsh/input/fsh/CapabilityStatement/SDOGestionnaire.fsh
> +* rest.resource[=].profile = "https://interop.esante.gouv.fr/ig/fhir/sdo/StructureDefinition/sdo-document-reference"
+ pas d'opération update de prévue sur la ressource task

2024-03-26 08:30 UTC, jguihot approved these changes
Zut il en restait un qui n'était pas partie. OK pour moi pour merge après cette dernière modif

2024-03-26 08:43 UTC, merged