fix issue 96
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #172
Opened 2024-03-26 11:07 UTC by TristanKEREVAL

Modification règle de conformité et slicing identifier DocumentReferenceSDO

## Description des changements

* Modif et renommage de la règle de gestion vérifiant l'adéquation entre le nom de la pièce jointe et le type de document
* [Modification de la SD SDODocumentReference pour les identifiers, mise en place d'un slicing

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-03-29 15:31 UTC, jguihot commented
@TristanKEREVAL , des travaux à prévoir également sur la ressource SDOTask :

- [ ] - regle ModePriseEnCharge à poser sur l'élément

- [ ] Revoir l'écriture de la règle, difficile à lire, manque des guillemets à certains endroits. Simplification proposée :
"Les codes possibles pour le mode de prise en charge sont : 46 (Hébergement (accueil jour et nuit)) ; 47 (Accueil de jour); 48 (Accueil de nuit)"

- [ ]  uniformiser les descriptions entre motifUnite et motifESMS (pas placés au même niveau, favoriser le niveau value pour la description de la table d'association)

2024-04-02 07:22 UTC, TristanKEREVAL commented
> @TristanKEREVAL , des travaux à prévoir également sur la ressource SDOTask :
> 
>     * [x]  - regle ModePriseEnCharge à poser sur l'élément
> 
>     * [x]  Revoir l'écriture de la règle, difficile à lire, manque des guillemets à certains endroits. Simplification proposée :
>       "Les codes possibles pour le mode de prise en charge sont : 46 (Hébergement (accueil jour et nuit)) ; 47 (Accueil de jour); 48 (Accueil de nuit)"
> 
>     * [x]   uniformiser les descriptions entre motifUnite et motifESMS (pas placés au même niveau, favoriser le niveau value pour la description de la table d'association)

Fix

2024-04-02 08:47 UTC, jguihot approved these changes
modif mineures à prévoir

2024-04-02 09:04 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDOTask.fsh
Ligne 76 : modification de texte proposé pour supprimer toute notion de valeur de statut et uniformiser la description avec le motif de l'ESMS:
"Permet de définir le motif associé au statut de l’usager dans l'unité"

2024-04-02 09:28 UTC, jguihot requested changes

2024-04-02 09:28 UTC, jguihot commented on input/fsh/input/fsh/profiles/ESMSDocumentReference.fsh
>  * type ^short = "Si la ressource contient le document CDA portant les données de individu et la décision : Code =  « 57830-2 » de la nomenclature LOINC docTypeCodes, Display = Admission request Docum
Binding sur le valueSet à passer en "required".
Une description en short ne me paraît pas adaptée, nous imposons l'une ou l'autre des deux valeurs, c'est une contrainte appliquée. Propositions:
- Short : "Code identifiant le type de document CDA véhiculé dans la ressource (Individu et Décision ou Evaluation)"
- contrainte : "Code = « 57830-2 » (Admission request Document) pour un document CDA Individu et Décision. Code = « 51848-0 » (Evaluation note) pour un document CDA portant l'Evaluation

2024-04-02 09:28 UTC, jguihot commented on input/fsh/input/fsh/profiles/SDODocumentReference.fsh
> +* identifier ^slicing.discriminator.type = #value
commentaire posé au mauvais endroit. Je clôture

2024-04-02 13:18 UTC, jguihot commented
@TristanKEREVAL , vu ensemble, tu peux supprimer les mentions de display dans les différentes ressources, pour éviter d'avoir discordance entre nos spécifications et les LOINC qui peuvent avoir évolué en parallèle (ex : consent, evaluation note,...)

2024-04-02 13:57 UTC, jguihot approved these changes
All good for me

2024-04-02 14:01 UTC, TristanKEREVAL commented
@nriss Petite interrogation de notre côté : Sur ESMSDocumentReference on a rendu le binding de l'attribut "type" en Required.
Sauf que depuis cette modif, les exemples utilisant la LOINC comme "TRE" pour cette attribut retourne une erreur dans le QA : 
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/122813625/0af3455e-a57f-4fa6-8bb6-fdda5265b2be)
Une idée de comment faire ? Faudrait créer une TRE avec nos codes pour les référencer. Si on limite l'utilisation de l'attribut à 2 codes c'est envisageable mais ça fait un élément supplémentaire

2024-04-02 15:00 UTC, nriss requested changes
Un petit commentaire :)

2024-04-02 15:18 UTC, jguihot commented on input/fsh/input/fsh/invariants/regle-ModePriseEnCharge.fsh
> +Expression: "value.coding.code='48' or value.coding.code='47' or value.coding.code='46'"
Nous utilisons le ValueSet existant dans les NOS. Les valeurs sont effectivement beaucoup plus limitées dans le contexte de ce volet. Certaines des entrées du ValueSet sont très orientées sanitaire et ne seront par conséquent jamais exploitées dans un contexte MS. @SEBELIN aurais-tu un avis sur la question ?

2024-04-02 16:25 UTC, jguihot commented
@TristanKEREVAL , vu avec @nriss , nettoyage à prévoir dans l'arborescence de l'IG pour supprimer le niveau input/fsh et le doublon du sushi-config
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/135017301/461db2ff-ef68-43d6-b4db-9be07abcba54)

2024-04-03 09:08 UTC, SEBELIN approved these changes
OK pour moi.

2024-04-03 10:15 UTC, jguihot commented
> OK pour moi.

Hello @SEBELIN , top. Ne nous manque que ton input sur les VS (voir conversation ci-dessus)

2024-04-03 11:15 UTC, SEBELIN commented on input/fsh/input/fsh/invariants/regle-ModePriseEnCharge.fsh
> +Expression: "value.coding.code='48' or value.coding.code='47' or value.coding.code='46'"
Je vous rejoins. 
je serais partant pour un JDV dans les NOS

2024-04-03 13:34 UTC, jguihot commented on input/fsh/input/fsh/invariants/regle-ModePriseEnCharge.fsh
> +Expression: "value.coding.code='48' or value.coding.code='47' or value.coding.code='46'"
Vu avec @SEBELIN , issue créée pour création d'un JDV dans les NOS (https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/174). En revanche, pour ne pas bloquer la présente release, nous resterons sur le fonctionnement en règle de gestion actuel

2024-04-03 13:37 UTC, jguihot commented on input/fsh/input/fsh/invariants/regle-Type.fsh
> +Expression: "(coding.code='57830-2') or (coding.code='51848-0')"
@TristanKEREVAL , vu avec @SEBELIN , codes spécifiques au volet, qui seront, à terme, remplacés par des codes spécifiques dans le JDV NOS identifiant les types de document. Cette règle peut donc être remplacée par un JDV directement dans l'IG. A tester

2024-04-04 13:12 UTC, TristanKEREVAL commented
@nriss Pour le nouveau JDV qu'on a créé pour l'attribut DocumentReference.type du profil ESMSDocumentReference.
Dans ce JDV on a créé un JDV important les 2 codes possibles pour l'attribut depuis la LOINC.
Pour chacun de ses codes on a le choix de définir un display ou alors de laisser celui de la TRE source.
Dans notre cas, si on vient redéfinir un display, les exemples devront quand même utiliser le display issu de la TRE source sinon on a un message d'erreur.

Donc on a créé le jdv sans préciser les display des codes importés.

2024-04-04 15:28 UTC, nriss commented on input/fsh/valueSets/ESMSDocumentReferenceType.fsh
> +ValueSet: DocumentReferenceTypeESMSValueSet
Top! :) Peux-tu appliquer le profil ShareableValueset ?

2024-04-05 07:45 UTC, TristanKEREVAL commented on input/fsh/valueSets/ESMSDocumentReferenceType.fsh
> +ValueSet: DocumentReferenceTypeESMSValueSet
ok fixed

2024-04-05 13:18 UTC, jguihot commented
> @nriss Pour le nouveau JDV qu'on a créé pour l'attribut DocumentReference.type du profil ESMSDocumentReference. Dans ce JDV on a créé un JDV important les 2 codes possibles pour l'attribut depuis la LOINC, pour chacun des codes on a pas précisé les display pour être toujours à jour avec la TRE source.
> 
> Cela peut poser un problème de suivie en cas de modif de la TRE source mais comme pour toutes les autres TRE hors IG.
> 
> Ça te va ?

@TristanKEREVAL , vu avec @nriss , c'est effectivement la marche à suivre. Des incohérences similaires ont été relevées coté ANS. Ne pas indiquer les display dans les JDV est par conséquent la manière la plus safe d'être à jour et de ne pas générer d'incohérence

2024-04-08 08:30 UTC, TristanKEREVAL commented
@nriss  petite question, on a remarqué avec notre problème de règle de gestions, qu'on pouvait techniquement mettre plusieurs coding au sein d'un élément CodeableConcept, et donc avoir plusieurs code. Ainsi on peut avoir dans certains cas, des règles de gestions qui ne détectent pas les erreurs. Avec notre syntaxe actuelle on vérifie la présence d'un code correct sur l'attribut évalué, puis cette présence induit la présence d'un second élément. Mais si l'ont remplit une occurrence de CodeableConcept.coding avec le bon code et qu'une seconde occurrence apparait avec un code incorrect, le second code n'est pas vérifié.
De façon générale est ce que limiter la cardinalité de CodeableConcept.coding à 1..1 ? Pour s'assurer qu'on ait réellement qu'un seul code ? Ou alors doit on modifier la syntaxe de la règle de gestion pour vérifier les codes présent, et ensuite on vérifie pour chaque code ce qu'il induit ? Ou alors on laisse cette possibilité d'avoir plusieurs coding même si c'est peu probable d'un point de vue fonctionnel ?

PS : est ce que tu pourrais revenir sur ta demande de modification, elle est résolue mais le message "change requested" apparait toujours.

2024-04-08 12:31 UTC, nriss commented
Hello Tristan,

Merci pour ton commentaire, très intéressant! 

https://www.hl7.org/fhir/R4/datatypes.html#codeableconcept
C'est pas écrit clairement, mais j'avais interprété ici qu'il fallait que les codes soient synonymes, modulo une granularité différente.
Cependant, même avec cette information, impossible de vérifier techniquement que des codes soient similaires.

Je pense que c'est à discuter en fonction du contexte, mais si ce cas d'usage exclut toute possibilité d'avoir un second code, c'est ok pour moi :)

2024-04-08 13:51 UTC, merged

2024-04-08 13:53 UTC, jguihot commented
Toutes les demandes de modification ont été prises en compte et mergées sur la branche main