Issue66
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #183
Opened 2024-04-12 14:08 UTC by TristanKEREVAL

## Description des changements

* Nouvelle page de test
* Modification de l'arborescence : déplacement de la page "documentation"
* ...

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-04-12 14:41 UTC, nriss requested changes

2024-04-12 14:41 UTC, nriss commented on input/pagecontent/tests.md
> +[Présentation des validateurs](20231121_SI-ESMS_Validateurs.pdf)
Ca va être très difficile à maintenir, la probabilité d'avoir des liens morts dans le futur est très forte! Il n'y a pas meilleur moyen ?

2024-04-15 07:04 UTC, TristanKEREVAL commented on input/pagecontent/tests.md
> +[Présentation des validateurs](20231121_SI-ESMS_Validateurs.pdf)
@jguihot Une alternative possible ? On a pas une plateforme pour héberger ça ?

2024-04-15 07:30 UTC, jguihot commented on input/pagecontent/tests.md
> +[Présentation des validateurs](20231121_SI-ESMS_Validateurs.pdf)
@nriss , quand tu parles de lien mort, tu parles du lien vers le support ppt ou des résultats de validation au sein du ppt ? Le but ici était surtout de stocker dans l'IG tout ce qui, présentement, est transmis par mail.
L'idéal serait sûrement de pointer plutôt vers la doc gazelle, plus complète que la présentation ppt, et plus générique.
EVS : https://gazelle.ihe.net/gazelle-documentation/EVS-Client/user.html
GWT : https://gazelle.ihe.net/gazelle-documentation/Gazelle-Webservice-Tester/user.html
Est-ce que cette option te conviendrait mieux ?

2024-04-15 07:39 UTC, nriss commented on input/pagecontent/tests.md
> +[Présentation des validateurs](20231121_SI-ESMS_Validateurs.pdf)
Par lien mort j'entends : suffit de changer le nom du fichier et pas reporter la modification au niveau de l'URL et du coup le fichier ne sera plus accessible, globalement ça crée une dépendance à gérer

J'ai l'impression qu'avec gazelle le problème serait le même

Je propose:
- Soit on intègre en markdown tout dans l'IG
- Sauf si le besoin d'avoir ce fichier est justifié, on fait comme vous avez fait

2024-04-15 08:03 UTC, jguihot requested changes

2024-04-15 08:03 UTC, jguihot commented on input/pagecontent/tests.md
> +Le guide d'implémentation de l'ANS décrit sur [cette page le fonctionnement des tests sur la plateforme Gazelle](https://interop.esante.gouv.fr/ig/documentation/tests.html).
attention au positionnement des liens cliquables + ne décrit pas que la plateforme gazelle: 
"Le guide d'implémentation de l'ANS décrit sur [cette page] (https://interop.esante.gouv.fr/ig/documentation/tests.html) les différents outils de tests à disposition.

2024-04-15 08:03 UTC, jguihot commented on sushi-config.yaml
> +    Tests:
pas nécessaire d'ajouter une page, puisqu'il n'y en a qu'une. Accès direct depuis le menu test:
Tests : tests.html

2024-04-15 08:03 UTC, jguihot commented on input/pagecontent/tests.md
> +[Présentation des validateurs](20231121_SI-ESMS_Validateurs.pdf)
vu avec @nriss , ok pour remplacer par la doc gazelle

2024-04-15 08:05 UTC, SEBELIN approved these changes

2024-04-15 08:09 UTC, TristanKEREVAL commented on input/pagecontent/tests.md
> +La liste des validateurs présent sur la plateforme [https://interop.esante.gouv.fr/evs](https://interop.esante.gouv.fr/evs) et les ressources de conformité associées :
ok

2024-04-16 08:01 UTC, nriss approved these changes

2024-04-16 08:03 UTC, jguihot approved these changes

2024-04-16 08:04 UTC, merged