Creation & update example
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #184
Opened 2024-04-12 14:09 UTC by TristanKEREVAL

Creation example exemple-bundle-resultat-recherche-decision-evaluation-elements

## Description des changements

* Creation example exemple-bundle-resultat-recherche-decision-evaluation-elements

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-04-15 08:05 UTC, TristanKEREVAL commented
> Il y a des erreurs avec sushi

fixed @nriss

2024-04-15 08:18 UTC, nriss approved these changes
ok :)

2024-04-15 10:31 UTC, jguihot requested changes

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Description: "Exemple de ressource Bundle suivant le profil ESMSBundleResultatRechercheDecisionEvaluation "
revoir la description, elle est en tout point identique à la description de l'autre exemple, ce qui rend impossible la compréhension de son usage. 
"Exemple de ressource Bundle suivant le profil ESMSBundleResultatRechercheDecisionEvaluation et modifié par une requête utilisant le paramètre _elements"

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Title: "exemple-bundle-resultat-recherche-decision-evaluation"
manque -elements. Les deux exemples s'affichent présentement avec le même nom

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Instance: exemple-esms-documentreference-elements-1-in-bundle
manque -elements

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Instance: exemple-esms-documentreference-elements-2-in-bundle
manque -elements

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-esms-document-reference.fsh
Je ne suis pas certaine d'avoir compris pourquoi tu as retiré les use ? En dépit du passage en slice, le use reste obligatoire. Dans tes exemples de bundle tu les as d'ailleurs conservé

2024-04-15 10:31 UTC, jguihot commented on input/fsh/instances/exemple-sdo-document-reference.fsh
même remarque

2024-04-15 10:50 UTC, TristanKEREVAL commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Description: "Exemple de ressource Bundle suivant le profil ESMSBundleResultatRechercheDecisionEvaluation "
fixed

2024-04-15 11:03 UTC, TristanKEREVAL commented on input/fsh/instances/exemple-esms-document-reference.fsh
Enfait le use est fixé via la slice, et fsh a juste besoin du nom de la slice et va automatiquement ajouter les attributs liés

2024-04-15 11:11 UTC, TristanKEREVAL commented on input/fsh/instances/exemple-bundle-resultat-recherche-decision-evaluation_elements.fsh
> +Title: "exemple-bundle-resultat-recherche-decision-evaluation"
fixed

2024-04-15 11:57 UTC, jguihot commented on input/fsh/instances/exemple-esms-document-reference.fsh
I see, dans ce cas, le fonctionnement devrait être le même pour le bundle non ? Or pour le bundle le use est toujours indiqué

2024-04-15 11:57 UTC, TristanKEREVAL commented on input/fsh/instances/exemple-esms-document-reference.fsh
yes c'est fix !

2024-04-16 07:54 UTC, jguihot approved these changes

2024-04-16 07:55 UTC, merged