Issues173
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #185
Opened 2024-04-12 14:12 UTC by TristanKEREVAL

## Description des changements

* Ajout des CapabilityStatement dans la liste des ressources FHIR
* [changement 2]
* ...

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-04-12 14:39 UTC, nriss commented on input/pagecontent/liste_profils.md
> +| CapabilityStatement  |  Description |
Essayer avec la requête

{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}

Ca devrait marcher en copiant-collant!

2024-04-12 14:39 UTC, nriss requested changes
Cf commentaire

2024-04-12 14:42 UTC, nriss commented
Peux-tu également mettre un titre plus explicite sur les deux issues pour faciliter la traçabilité dans le changelog ? Merci! :)

2024-04-15 07:00 UTC, TristanKEREVAL commented on input/pagecontent/liste_profils.md
> +| CapabilityStatement  |  Description |
OK

2024-04-15 08:02 UTC, SEBELIN approved these changes

2024-04-15 10:35 UTC, jguihot commented
@TristanKEREVAL , description à mettre à jour pour ne conserver que les évol faites + MAJ du lien vers le preview

2024-04-15 10:44 UTC, jguihot requested changes

2024-04-15 10:44 UTC, jguihot commented on input/pagecontent/liste_profils.md
> +{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}
Pas un seul title identique sur les CS. CS à uniformiser pour avoir le même format.

@nriss , j'utiliserais plutôt le name dans la requête plutôt que le title non ? Le title a présentement un formatage assez long reprenant le nom du volet, ce qui présente peu d'intérêt.
ex : name = ESMSProducteur / title = ​CI-SIS - Suivi-Des-Orientations - Producteur - SI-ESMS
Ou bien il faudrait inverser les valeurs des name et title ?

2024-04-15 11:28 UTC, nriss commented on input/pagecontent/liste_profils.md
> +{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}
J'ai choisi le Titre dans le cadre des profils car c'est celui qui est utilisé dans la page du profil : 

https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-device.html
<img width="1200" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/61dceaeb-0f47-408b-9ae0-c50e9ffd38bb">


C'est également le titre utilisé dans le cadre des CS : 
<img width="1386" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/f01ee153-7dbb-4a9f-9819-a9c429c357d5">


Il faut donc peut être mettre à jour les titres pour avoir qqc de plus clair.

A. noter qu'il faut également changer "StructureDefinition-" par "CapabilityStatement-" pour rendre les urls accessibles

2024-04-15 11:48 UTC, TristanKEREVAL commented on input/pagecontent/liste_profils.md
> +{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}
requête modifiée

2024-04-15 12:02 UTC, jguihot commented on input/pagecontent/liste_profils.md
> +{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}
Du message de Nicolas, je comprenais que la requête n'était pas à modifier, mais les CS à retravailler

2024-04-15 12:51 UTC, jguihot commented on input/pagecontent/liste_profils.md
> +{% sql SELECT '[' || Title ||'](StructureDefinition-' || id || '.html)' as "Titre du profil", Description FROM Resources WHERE Type = 'CapabilityStatement' %}
Title proposés : 
- SI-ESMS-Producteur
- SI-ESMS-Consommateur
- SI-SdO-Gestionnaire

2024-04-15 13:02 UTC, nriss approved these changes
Ok pour moi sous réserve de changement de titres conformément a ce qu'à proposé @jguihot 

> Title proposés :
> 
> * SI-ESMS-Producteur
> * SI-ESMS-Consommateur
> * SI-SdO-Gestionnaire

2024-04-16 08:01 UTC, jguihot approved these changes

2024-04-16 08:01 UTC, merged