Modification de la page liste de profils et ajout d'une description à…
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #225
Opened 2024-09-30 12:01 UTC by TristanKEREVAL

… toutes les ressources

## Description des changements

* Ajout d'une description à toutes les ressources
* Modification du tableau contenant la liste des ressources, séparation en 2 tableau vis à vis du volet auxquelles les ressources appartiennent
* ...

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-09-30 12:23 UTC, nriss approved these changes
Top! Très propre comme ça

2024-09-30 16:20 UTC, jguihot requested changes
Il faudra également mettre à jour la page index.md. Idéalement il aurait fallu ne lister qu'une seule fois les profils sur cette page, mais en faisant de la sorte nous perdrions la colonne listant les volets concernés, je pense qu'il faudra donc passer ici aussi par deux tableaux

2024-09-30 16:20 UTC, jguihot commented on input/fsh/profiles/SDOBundleResultatRechercheNotificationESMS.fsh
Il s'agit d'un profil SDO-ESMS

2024-09-30 16:20 UTC, jguihot commented on input/fsh/profiles/ESMSDocumentReference.fsh
> +Description: "Profil ESMS pour définir le dossier ESMS"
Compléter la définition pour reprendre la définition qui était disponible initialement dans liste_profils

2024-09-30 16:20 UTC, jguihot commented on input/fsh/profiles/SDODocumentReference.fsh
> +Description: "Profil SDO pour définir le dossier SDO"
Compléter la définition pour reprendre la définition qui était disponible initialement dans liste_profils

2024-10-01 07:10 UTC, TristanKEREVAL commented on input/fsh/profiles/ESMSDocumentReference.fsh
> +Description: "Profil ESMS pour définir le dossier ESMS"
En gardant le mot clé "générique"dans la description ?

2024-10-01 07:11 UTC, TristanKEREVAL commented on input/fsh/profiles/SDODocumentReference.fsh
> +Description: "Profil SDO pour définir le dossier SDO"
En gardant le mot clé "générique"dans la description ? @jguihot

2024-10-01 07:25 UTC, jguihot commented on input/fsh/profiles/ESMSDocumentReference.fsh
> +Description: "Profil ESMS pour définir le dossier ESMS"
Non, du coup tu peux t'affranchir de cette notion pour reprendre la base que tu as déjà, juste la compléter: "Profil ESMS héritant du profil SDODocumentReference. Profil utilisé pour véhiculer les données de l'individu et de la décision, ou les données de l'évaluation dans un document CDA" ?

2024-10-01 07:26 UTC, jguihot commented on input/fsh/profiles/SDODocumentReference.fsh
> +Description: "Profil SDO pour définir le dossier SDO"
Non, du coup tu peux t'affranchir de cette notion pour reprendre la base que tu as déjà, juste la compléter: "Profil SDO utilisé pour véhiculer les données de l’individu, la décision et l’évaluation contenus dans le document CDA" ?

2024-10-01 07:44 UTC, TristanKEREVAL commented
Modif effectuée @jguihot

2024-10-01 12:49 UTC, nriss commented
D'ailleurs, c'est un peu dommage d'avoir enlevé la page artifacts.html qui a également les exemples et tout : 
https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/180-rc-synth%C3%A8se-des-ressources/ig/artifacts.html

En général, je laisse les deux (cf exemple de l'annuaire qui a la liste des profils mais aussi une page ressources de conformité

Par habitude je trouve ça pratique d'avoir la page artifacts

2024-10-01 17:28 UTC, jguihot requested changes

2024-10-01 17:28 UTC, jguihot commented on input/pagecontent/index.md
> +### Profils utilisés pour le volet SI-ESMS
Modifier le niveau du titre en position 5 #####

2024-10-01 17:28 UTC, jguihot commented on input/pagecontent/index.md
> +### Profils utilisés pour le volet SI-SDO
Modifier le niveau du titre en position 5 #####

2024-10-01 17:35 UTC, jguihot commented
> D'ailleurs, c'est un peu dommage d'avoir enlevé la page artifacts.html qui a également les exemples et tout : https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/180-rc-synth%C3%A8se-des-ressources/ig/artifacts.html
> 
> En général, je laisse les deux (cf exemple de l'annuaire qui a la liste des profils mais aussi une page ressources de conformité
> 
> Par habitude je trouve ça pratique d'avoir la page artifacts

L'information me semble redondante non ? Est-ce que ça ne prête pas à confusion de lister deux fois les profils mais sous une présentation différente ? Nous pouvons peut être envisager de compléter la page actuelle en rapatriant les autres tableaux du Artifacts summary ? Nous n'utilisons pas de searchParameters il me semble et je ne pense pas que nous utilisions non plus d'extension. Resterait donc surtout les terminologies.

2024-10-02 07:48 UTC, nriss commented
Il y a une partie redondante effectivement.. En fait, étant habitué aux IGs, je me dis :
- La page artifact est pratique car elle a toujours le même format, quel que soit le guide, et donne rapidement une vision du guide (quand il n'y a pas de lien, je tape directement dans l'url généralement pour trouver la page)
- Le fait d'avoir ce bouton permet d'avoir tjs le même format d'un IG à l'autre, avec tjs accès à la page ressources de conformité

Mais je peux comprendre que ça peut être ambigu
Ok pour laisser tel quel en rajoutant CapabilityStatement, CS, VS, et instances :)

2024-10-02 07:53 UTC, nriss approved these changes

2024-10-02 08:28 UTC, TristanKEREVAL commented
Changement ajouté @jguihot

2024-10-02 09:53 UTC, jguihot commented
> Il y a une partie redondante effectivement.. En fait, étant habitué aux IGs, je me dis :
> 
> * La page artifact est pratique car elle a toujours le même format, quel que soit le guide, et donne rapidement une vision du guide (quand il n'y a pas de lien, je tape directement dans l'url généralement pour trouver la page)
> * Le fait d'avoir ce bouton permet d'avoir tjs le même format d'un IG à l'autre, avec tjs accès à la page ressources de conformité
> 
> Mais je peux comprendre que ça peut être ambigu Ok pour laisser tel quel en rajoutant CapabilityStatement, CS, VS, et instances :)

Vendu, on part là-dessus alors. Nous allons au passage renommer le .md qui s'appelle actuellement liste_profils et qui ne serait pas approprié pour contenir des VS et exemple. Nous allons uniformiser avec le .md CDA pour qu'il devienne ressources_fhir

2024-10-02 13:30 UTC, TristanKEREVAL commented
fixed @nriss @jguihot

2024-10-02 14:45 UTC, nriss commented
Il manque les liens pour les instances

2024-10-03 09:12 UTC, TristanKEREVAL commented
> Il manque les liens pour les instances

Fixed ! @jguihot @nriss

2024-10-03 12:23 UTC, merged