229 format de la date dernière recherche flux 11 et flux 51
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #231
Opened 2024-10-03 08:02 UTC by TristanKEREVAL

## Description des changements

* Modification des descriptions des paramètres de recherche de type date pour le flux 1.1 et 5.1

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-10-03 08:32 UTC, SEBELIN approved these changes
OK pour moi. A noter qu'il y a peut être un impact sur les validateurs de requête du flux 1.1 et 5.1.

2024-10-03 08:56 UTC, TristanKEREVAL commented
@SEBELIN Je viens de vérifier et ça ne devrait pas avoir d'impact, à confirmer @jguihot

2024-10-03 12:01 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +* [dateDernièreRecherche] est au format Année-Mois-Jour-Heure
format YYYY-MM-DDThh:mm:ss+zz:zz

2024-10-03 12:12 UTC, jguihot requested changes

2024-10-03 12:12 UTC, jguihot commented on input/pagecontent/st_flux5.md
> +-	[dateDernièreRecherche] est au format Année-Mois-Jour-Heure
format YYYY-MM-DDThh:mm:ss+zz:zz

2024-10-03 12:31 UTC, TristanKEREVAL commented
> Evolution à prévoir sur le validateur. Le paramètre est bien au format Date, qui supporte le format dateTime, mais pour correspondre au besoin de ce volet, le regex doit être modifié pour imposer l'heure (facultative pour le moment)

Je reprendrai le regex du dataType Instant (type de l'attribut _lastUpdated)de la spec FHIR (http://hl7.org/fhir/R4/datatypes.html#primitive)
Regex: ([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))

2024-10-03 12:35 UTC, jguihot commented
> > Evolution à prévoir sur le validateur. Le paramètre est bien au format Date, qui supporte le format dateTime, mais pour correspondre au besoin de ce volet, le regex doit être modifié pour imposer l'heure (facultative pour le moment)
> 
> Je reprendrai le regex du dataType Instant (type de l'attribut _lastUpdated)de la spec FHIR (http://hl7.org/fhir/R4/datatypes.html#primitive) Regex: ([0-9](%5B0-9%5D(%5B0-9%5D%5B1-9%5D%7C%5B1-9%5D0)%7C%5B1-9%5D00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(.[0-9]+)?(Z|(+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))

ce paramètre est permissif et permet aussi bien de renseigner année que année-mois-jour-heure-minute-seconde. Or ces ce dernier format qu'on impose

2024-10-03 12:55 UTC, TristanKEREVAL commented
Utiliser le regex définit en R5 : ([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(
[01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]{1,9})?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]
|14:00))

2024-10-04 06:50 UTC, TristanKEREVAL commented
fixed @jguihot

2024-10-04 08:27 UTC, jguihot approved these changes
OK. 
@nriss , plutôt format technique pour le format des dates ? Ou ce format fonctionnel est OK ?

2024-10-04 08:28 UTC, nriss requested changes

2024-10-04 08:28 UTC, nriss commented on input/pagecontent/st_flux1.md
> +* [dateDernièreRecherche] est au format Année-Mois-JourTHeure:minutes:secondes+FuseauHoraire
Peut être mettre le lien vers la regex FHIR plutôt que de réécrire la doc ? Ca sensibilisera à chercher l'info sur la doc officielle

2024-10-04 08:49 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +* [dateDernièreRecherche] est au format Année-Mois-JourTHeure:minutes:secondes+FuseauHoraire
du coup plutôt quelque chose du style : "est au format instant (lien vers la doc ?)"

2024-10-04 08:54 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +* [dateDernièreRecherche] est au format Année-Mois-JourTHeure:minutes:secondes+FuseauHoraire
Parfait, @TristanKEREVAL , tu peux prendre en compte ?

2024-10-04 12:36 UTC, TristanKEREVAL commented on input/pagecontent/st_flux1.md
> +* [dateDernièreRecherche] est au format Année-Mois-JourTHeure:minutes:secondes+FuseauHoraire
Fixed @jguihot @nriss

2024-10-04 12:43 UTC, nriss approved these changes

2024-10-04 12:43 UTC, nriss requested changes

2024-10-04 12:43 UTC, nriss commented on input/pagecontent/st_flux5.md
> +En cas d’échec, le SI-SDO doit répondre avec le code HTTPS approprié tel que défini par l’API REST FHIR [(Http - FHIR v4.0.1 (hl7.org))](https://hl7.org/fhir/http.html). Une ressource OperationOutcom
Attention le lien redirige vers R5

2024-10-04 13:34 UTC, jguihot commented on input/pagecontent/st_flux5.md
> +En cas d’échec, le SI-SDO doit répondre avec le code HTTPS approprié tel que défini par l’API REST FHIR [(Http - FHIR v4.0.1 (hl7.org))](https://hl7.org/fhir/http.html). Une ressource OperationOutcom
hors contexte de cette PR et potentiellement plus large en terme d'impact. A étudier => issue créée #233

2024-10-04 14:44 UTC, merged