Modification Flux 3.1
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #245
Opened 2024-10-09 12:05 UTC by TristanKEREVAL

## Description des changements

* Modif nom du flux sur les différents diagrammes,
* Modif des descriptions
* Suppressions du paramètre _elements de la requêtre 3.1
* Modif du nom de l'onglet

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-10-09 13:48 UTC, TristanKEREVAL commented
Fixed @jguihot

2024-10-09 14:55 UTC, TristanKEREVAL commented
Validateur modifié en pprod

2024-10-09 15:16 UTC, jguihot requested changes
@TristanKEREVAL nom du validateur à MAJ sur tests.md

2024-10-09 16:15 UTC, jguihot commented
+ en attente de validation de @SEBELIN pour éventuels impacts Ségur

2024-10-10 07:42 UTC, nriss commented on input/images-source/flux3.plantuml
> +ESMS-[#black]> SDO : Flux 3.1 **ConsultationEvaluation** \n <color #FireBrick>GET [base]/DocumentReference?identifier=[idNat-Decision]&type=51848-0</color>
Qu'est-ce qui a invité au changement de nom ? J'aime bien recherche de mon côté pcq c'est comme dans PDSm où on utilise également le terme "recherche" et que ça renvoie à la search de FHIR

2024-10-10 09:22 UTC, jguihot commented on input/images-source/flux3.plantuml
> +ESMS-[#black]> SDO : Flux 3.1 **ConsultationEvaluation** \n <color #FireBrick>GET [base]/DocumentReference?identifier=[idNat-Decision]&type=51848-0</color>
L'idée était ici de proposer un nommage qui corresponde à l'action qui sera faite, en l'occurrence consulter un unique document. Par cette recherche il n'est pas possible de remonter plus d'un document. Toutefois, cela reste une opération search, le terme recherche est peut être plus en accord.

2024-10-10 09:57 UTC, jguihot commented on input/images-source/flux3.plantuml
> +ESMS-[#black]> SDO : Flux 3.1 **ConsultationEvaluation** \n <color #FireBrick>GET [base]/DocumentReference?identifier=[idNat-Decision]&type=51848-0</color>
@TristanKEREVAL , rollback sur ces modifications. Ne conserver que la suppression du _elements. A tracer dans l'issue

2024-10-10 13:15 UTC, closed without merging

2024-10-10 13:15 UTC, jguihot commented
Suppression de cette PR pour en rouvrir un autre avec seulement les modif de diagrammes