Mise à jour du XSD_MS_20240424.zip
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #254
Opened 2024-10-29 15:04 UTC by KerJac35

## Description des changements

Mise à jour du XSD :
- Suppression du fichier "Nomenclatures"
- Tous les éléments de type Code ont été changés en type "CE" dans l'extension SDO

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/Validateur_CDA-Ajout_JDV_J264/ig

2024-11-04 21:53 UTC, jguihot requested changes
Le nom de la branche ne correspond pas du tout à la PR

dossier à mettre à jour

2024-11-20 22:00 UTC, jguihot commented
@KerJac35 , ça n'est pas la version 20241009 qui est accessible, mais toujours la V20240424. A mettre à jour

2024-11-22 17:49 UTC, jguihot approved these changes

2024-11-25 08:58 UTC, SEBELIN approved these changes

2024-11-25 09:03 UTC, merged