Modification des tabeaux
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #284
Opened 2024-12-03 15:59 UTC by TristanKEREVAL

Re-écriture des tableaux en markdown

## Description des changements

* Réécriture du tableau sur la page annexes_Glossaire.md
* Réécriture du tableau sur la page annexes_nomenclatures.md
* Réécriture du tableau sur la page annexes_nomenclatures_precision.md
* Réécriture du tableau sur la page annexes_OID_MDPH.md

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-12-12 09:12 UTC, KerJac35 commented on input/pagecontent/annexes_Nomenclature.md
> +| Nomenclatures CNSA                             | NO_*              | NomenclatureCNSA_V2.8.xlsm                      |
Il manque le lien vers le fichier excel des nomenclatures CNSA

2024-12-12 09:24 UTC, KerJac35 commented on input/pagecontent/annexes_Nomenclatures_precision.md
> +| 11.3 Orientation vers l'unité d'évaluation, de réentraînement et d'orientation sociale et socioprofessionnelle (UEROS) | pas de précision                            |
Le libellé exact ici doit être : Orientation vers l'unité d'évaluation, de réentraînement et d'orientation sociale et socioprofessionnelle pour personnes cérébro-lésées (UEROS)

2024-12-12 09:39 UTC, KerJac35 requested changes
Fichier annexes_Nomenclatures. md -> Il manque le lien vers le fichier excel des nomenclatures CNSA

Fichier annexes_Nomenclatures_precision.md -> Libellé du code 11.3 à revoir

2024-12-12 14:33 UTC, TristanKEREVAL commented
Fixed ! @KerJac35

2024-12-12 16:52 UTC, KerJac35 approved these changes

2024-12-12 16:52 UTC, KerJac35 commented
Ok de mon côté, en attente de validation ANS

2024-12-13 08:41 UTC, nriss approved these changes
Beaucoup plus lisible! merci :)

2024-12-13 08:56 UTC, SEBELIN approved these changes

2024-12-13 08:58 UTC, merged