Modification des URLS vers la spec R4
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #285
Opened 2024-12-04 12:39 UTC by TristanKEREVAL

## Description des changements

* Modification de tous les URLS pointant vers la spec FHIR, pour référencer la spec R4
* Fichiers concernés : 
** README.md
** aliases.fsh
** SDOTaskInputCS
** ESMSDocumentReferenceType
** ignoreWarnings
** downloads
** index
** st_flux 1 à 5

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-12-05 12:58 UTC, nriss requested changes
A corriger, l'url canonique des ressources de conformité ne contiennent pas R4

ex : https://hl7.org/fhir/R4/StructureDefinition/shareablecodesystem n'est pas une bonne url canonique

2024-12-11 08:29 UTC, nriss commented on input/fsh/aliases.fsh
> +Alias: $DocumentType = https://hl7.org/fhir/R4/ValueSet/c80-doc-typecodes
Idem url canonique

2024-12-11 08:29 UTC, nriss commented on input/pagecontent/downloads.md
> +Vous pourrez ensuite utiliser l'opération [$validate](https://www.https://https://hl7.org/fhir/R4/resource-operation-validate.html) pour valider les instances de ressource contre un profil issu de ce
A corriger

2024-12-11 08:29 UTC, nriss commented on input/pagecontent/index.md
> +* Le standard [HL7 FHIR v4.0.1](https://www.https://hl7.org/fhir/R4/) pour le transport.
A corriger

2024-12-11 08:29 UTC, nriss commented on input/pagecontent/st_flux1.md
> +                    <p style='margin-top:3.0pt;margin-right:0cm;margin-bottom:6.0pt;margin-left:0cm;text-align:justify;line-height:115%;font-size:12px;font-family:"Arial",sans-serif;'><span style="co
a corriger

2024-12-11 10:51 UTC, nriss commented on input/fsh/codesystems/SDOTaskInputCS.fsh
> +* ^meta.profile = "https://hl7.org/fhir/StructureDefinition/shareablecodesystem"
Pas de https ?
<img width="922" alt="image" src="https://github.com/user-attachments/assets/fd72b5be-ccbd-4f91-ae5c-8531e04cd67d">

2024-12-11 10:52 UTC, nriss commented on input/fsh/aliases.fsh
> +Alias: $DocumentType = https://hl7.org/fhir/ValueSet/c80-doc-typecodes
Sûr que c'est en https ?

2024-12-11 11:00 UTC, TristanKEREVAL commented on input/fsh/aliases.fsh
> +Alias: $DocumentType = https://hl7.org/fhir/ValueSet/c80-doc-typecodes
Le lien ne résout dans aucun des cas, mais l'alias n'est appelé nul part au final. On peut supprimer cette ligne je pense

2024-12-11 13:16 UTC, nriss commented on input/fsh/aliases.fsh
> +Alias: $DocumentType = https://hl7.org/fhir/ValueSet/c80-doc-typecodes
Ok pour supprimer!

2024-12-11 13:18 UTC, nriss commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
A quoi sert ce fichier ?

2024-12-11 13:40 UTC, jguihot commented on input/fsh/aliases.fsh
> +Alias: $DocumentType = https://hl7.org/fhir/ValueSet/c80-doc-typecodes
c'était ce JDV initialement sur le type de documentReference : https://hl7.org/fhir/R4/valueset-c80-doc-typecodes.html. Mais il a été remplacé par un JDV propre à l'IG restreignant à 2 valeurs : [DocumentReferenceTypeESMSValueSet](https://interop.esante.gouv.fr/ig/fhir/sdo/ValueSet-type-document-reference-esms-valueset.html)

2024-12-11 15:05 UTC, TristanKEREVAL commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
Je ne sais pas trop, ça te parle @jguihot ?

2024-12-11 15:44 UTC, jguihot commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
@nriss , @TristanKEREVAL , ce fichier provient de l'IG-modele. Aucune idée de ce à quoi il sert

2024-12-11 16:05 UTC, nriss commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
Ok dans ce cas vous pouvez le supprimer!
C'est un fichier pour supprimer des warnings et erreurs du QA

2024-12-11 16:05 UTC, nriss approved these changes
Ok après avoir supprimé le fichier input/ignoreWarnings.txt :)

2024-12-12 07:55 UTC, jguihot commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
tracé dans l'issue #292 . 
@nriss , sans trop savoir concrètement ce que fait ce fichier, je préfère que nous prenions le temps d'observer les impacts de sa suppression pour ne pas risquer des anomalies alors que nous n'avons qu'1 semaine pour effectuer l'intégralité des évolutions demandées par l'ANS.
D'autant que cette suppression n'a pas de lien avec cette PR ;-)

2024-12-12 07:56 UTC, nriss commented on input/ignoreWarnings.txt
>  # (And include comments like this justifying why)
Parfait!

2024-12-12 16:07 UTC, KerJac35 approved these changes

2024-12-12 16:09 UTC, merged