ANS-006-140 - MAJ de l'identité du patient (contraintes INS)
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #291
Opened 2024-12-11 17:04 UTC by jguihot

## Description des changements

* Ajout de la civilité (facultatif) dans le name du patient
* Mise à jour des contraintes liées à l'INS

## Preview

https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/[ajouter_nom_de_la_branche]/ig

2024-12-12 15:43 UTC, nriss approved these changes
Je te fais confiance :)
Difficile à review et à mettre à jour ces tableaux

2024-12-12 17:11 UTC, jguihot commented
Effectivement, gros refactoring en attente sur cette page. Impossible de faire des ajouts / correction sans conserver la mise en forme embarquée ce qui rend les mises à jour très complexes à mettre en œuvre

2024-12-13 10:17 UTC, KerJac35 requested changes
Concernant l'issue #281 : Il manque la modification des exemples CDA_Decision et CDA_Evaluation. Il faut remplacer : 

<cnsaSDO:numSecuriteSocialeOuvrantDroit>276059205062865</cnsaSDO:numSecuriteSocialeOuvrantDroit>

par : 

<cnsaSDO:numSecuriteSocialeOuvrantDroit extension="276059205062865" root="1.2.250.1.213.1.4.13"/>


Concernant l'issue #242 : 

![image](https://github.com/user-attachments/assets/63ec7d83-cd82-4742-b580-c0aa2fc565be)

Est-ce normal que l'on ait la mention "(information de l’INS)" pour le Nom d'usage ?

2024-12-13 13:50 UTC, SEBELIN commented
*
Je confirme que l'extension est un identifiant.
  *
pour le nom d'usage comme pour les autres traits INS il faudrait remettre ce qui est écrit dans l'annexe INS
Pour rappel, l’INS est composé des éléments suivants :
     *
• le matricule INS et l’identifiant de l’organisme qui gère et garantit l’unicité de l’INS sous la forme d’un OID (autorité d’affectation) ;
• le nom de naissance, la liste des prénoms de naissance, le sexe, la date et le lieu de naissance = traits stricts INS


Le RNIV complète l’INS avec d’autres traits obligatoires ou non :
• premier prénom de naissance, obligatoire ;
• nom utilisé, obligatoire lorsqu’il est différent du nom de naissance ;
• prénom utilisé, obligatoire lorsqu’il est différent du premier prénom de naissance.

  *



Agence du Numérique en Santé

Eric SEBELIN



Expert

Tél.



+33158456244



________________________________
De : KerJac35 ***@***.***>
Envoyé : vendredi 13 décembre 2024 14:22
À : ansforge/IG-fhir-medicosocial-suivi-decisions-orientation ***@***.***>
Cc : Eric SEBELIN ***@***.***>; Mention ***@***.***>
Objet : Re: [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation] ANS-006-140 - MAJ de l'identité du patient (contraintes INS) (PR #291)


@KerJac35 requested changes on this pull request.

Concernant l'issue #281<https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/281> : Il manque la modification des exemples CDA_Decision et CDA_Evaluation.
@SEBELIN<https://github.com/SEBELIN> il faudrait changer le type "string" par "identifiant" pour l'attribut cnsa:numSecuriteSocialeOuvrantDroit est ce que tu valides ? Si oui dans les exemples il faudrait modifier :

"cnsaSDO:numSecuriteSocialeOuvrantDroit276059205062865</cnsaSDO:numSecuriteSocialeOuvrantDroit>"

par :

"<cnsaSDO:numSecuriteSocialeOuvrantDroit extension="276059205062865" root="1.2.250.1.213.1.4.13"/>"

Concernant l'issue #242<https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/242> :

image.png (view on web)<https://github.com/user-attachments/assets/63ec7d83-cd82-4742-b580-c0aa2fc565be>

Est-ce normal que l'on ait la mention "(information de l’INS)" pour le Nom d'usage ?

—
Reply to this email directly, view it on GitHub<https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/291#pullrequestreview-2501937643>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDBEGRDU24P547TTKPU3WML2FLNQHAVCNFSM6AAAAABTN6F43GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBRHEZTONRUGM>.
You are receiving this because you were mentioned.

2024-12-16 09:27 UTC, SEBELIN commented
Je confirme de modifier le type de données en type identifiant.




Agence du Numérique en Santé

Eric SEBELIN



Expert

Tél.



+33158456244



________________________________
De : Jeanne GUIHOT ***@***.***>
Envoyé : vendredi 13 décembre 2024 20:13
À : ansforge/IG-fhir-medicosocial-suivi-decisions-orientation ***@***.***>
Cc : Eric SEBELIN ***@***.***>; Mention ***@***.***>
Objet : Re: [ansforge/IG-fhir-medicosocial-suivi-decisions-orientation] ANS-006-140 - MAJ de l'identité du patient (contraintes INS) (PR #291)


@SEBELIN<https://github.com/SEBELIN> , les évolutions ont déjà été implémentées (voir lien de la branche).

Concernant le numéro de sécurité social, ce que Jérémie te disait, c'est qu'actuellement, dans les spécifications, il ne s'agit pas d'un identifiant, mais d'un champs texte. Pour implémenter les évolutions demandées par Alain, il faut par conséquent changer le type de la donnée pour le passer de texte à Identifiant. Impact éditeur donc. Tu confirmes bien que nous implémentons cette modification de type de données ?

—
Reply to this email directly, view it on GitHub<https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/291#issuecomment-2542086887>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDBEGRHO2DB7L4VKYIJOHXD2FMWT3AVCNFSM6AAAAABTN6F43GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBSGA4DMOBYG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-12-16 16:27 UTC, SEBELIN commented
pour nom usage préciser : obligatoire lorsqu’il est différent du nom de naissance ;

2024-12-17 10:03 UTC, KerJac35 approved these changes
OK de mon côté, en attente de validation ANS

2024-12-17 10:08 UTC, SEBELIN approved these changes

2024-12-17 10:39 UTC, merged