Presta 98
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #49
Opened 2023-12-20 08:06 UTC by TristanKEREVAL

2024-01-05 20:16 UTC, jguihot requested changes
Review FHIR OK, reste review CDA à faire

2024-01-05 20:16 UTC, jguihot commented on input/images/20230706_Prod_ESMS_RecapValidateurs.xlsx
versionner le fichier avant de le soumettre

2024-01-05 20:16 UTC, jguihot commented on input/images-source/flux5.plantuml
>  La ressource Task véhiculant un statut
Supprimer "La" en début de texte

2024-01-05 20:16 UTC, jguihot commented on input/pagecontent/ressource_cda.md
Impossible d'avoir accès aux documents depuis la preview. @jguihot , à revérifier en local

2024-01-05 20:16 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +                    A noter que pour un cas nominal, la fr&eacute;quence de recherche est J-1. Pour un cas exceptionnel (premi&egrave;re connexion au SI-SDO d&rsquo;un DUI), la limite temporelle est
garder une cohérence dans l'écriture. J-1 => J-30

2024-01-08 12:02 UTC, jguihot commented on input/pagecontent/contenu_dossier.md
> +
voir commentaire de l'issue #38 , il ne fallait pas ajouter de règle de gestion, c'est le validateur qui sera à mettre à jour

2024-01-08 12:07 UTC, jguihot commented on input/pagecontent/contenu_dossier.md
Manque toute la section évaluation !

2024-01-08 12:15 UTC, jguihot commented on input/images/20231219_DiagrammeSequence_Global_V5.jpg
Le processus "consultation des autres statuts intermédiaires" est également à supprimer. Il s'agit d'une transmission de statut classique

2024-01-08 17:01 UTC, jguihot requested changes

2024-01-08 17:01 UTC, jguihot commented on input/pagecontent/st_flux1.md
texte à ajouter dans le tableau du flux 5

2024-01-09 13:52 UTC, TristanKEREVAL commented on input/pagecontent/annexes_Nomenclature.md
> +                <p style='margin:0cm;text-align:justify;line-height:115%;font-size:12px;font-family:"Arial",sans-serif;'><span style="color:black;"><a href="https://mos.esante.gouv.fr/NOS/](https://m
Corrigé

2024-01-09 14:34 UTC, TristanKEREVAL commented on input/FHIR/ESMSBundleResultatRechercheDecisionEvaluation.json
> Lignes 42 et 91 : supprimer les références aux auteurs (voir issue #25 )

Corrigé

2024-01-10 09:14 UTC, TristanKEREVAL commented on input/FHIR/ESMSBundleResultatRechercheDecisionEvaluation.json
> +							"title": "Document évaluation",
Ok, les 2 DR ont comme la valeur : Document Individu et décision

2024-01-10 09:20 UTC, TristanKEREVAL commented on input/FHIR/ESMSBundleResultatRechercheDecisionEvaluation.json
> idDecision1

cORRIG2

2024-01-10 09:20 UTC, TristanKEREVAL commented on input/FHIR/ESMSConsent.json
> +        "system": "http://terminology.hl7.org/5.0.0/CodeSystem/v3-ActCode",
Binding extensible donc on peut pointer vers autre chose si on trouve pas notre bonheur dans le premier jdv

2024-01-10 09:21 UTC, TristanKEREVAL commented on input/FHIR/StructureDefinition-esms-consent.json
On fige à quelle valeur ?

2024-01-10 09:43 UTC, TristanKEREVAL commented on input/FHIR/SDOBundleResultatRechercheNotificationESMS.json
>                    "system": "https://mos.esante.gouv.fr/NOS/TRE_R213-ModePriseEnCharge/",
fix

2024-01-10 09:46 UTC, TristanKEREVAL commented on input/images/20231219_DiagrammeSequence_Global_V5.jpg
Faut modifier l'uml et ensuite je peux la remettre

2024-01-10 09:49 UTC, TristanKEREVAL commented on input/images/image2.jpg
Je ne sais pas

2024-01-10 09:49 UTC, TristanKEREVAL commented on input/images/Image1.png
Je ne sais pas

2024-01-10 09:49 UTC, TristanKEREVAL commented on input/images/Image1.jpg
Je ne sais pas

2024-01-10 09:53 UTC, TristanKEREVAL commented on input/FHIR/StructureDefinition-esms-consent.json
> +				"short": "Valeur de l’identifier vers lequel la ressource Consent doit pointer (identifier officiel du documentReference = idNatDecision)"
Fix

2024-01-10 09:57 UTC, TristanKEREVAL commented on input/FHIR/StructureDefinition-sdo-document-reference.json
> +				"short": "La première occurence : identifiant de la décision unique au sein de la MDPH ayant créé la décision (idDecision) Identifier.use = « usual ». Deuxième occurence :  identifiant technique
Supprimé le "La" mais je n'ai psa compris la suite du point

2024-01-15 10:57 UTC, nriss requested changes
Je n'ai pas fini ma review, je la reprends plus tard :)

2024-01-15 10:57 UTC, nriss commented on input/FHIR/ESMSConsent_nonPassant.json
> -{
Le fichier a bien été supprimé ? Pourquoi est-ce que je n'ai pas le message "the file has been deleted" ?

2024-01-15 11:53 UTC, jguihot commented on input/FHIR/ESMSConsent.json
> +        "system": "http://terminology.hl7.org/5.0.0/CodeSystem/v3-ActCode",
@nriss , ne vaut-il pas mieux se fier à la doc FHIR qui pointe vers un autre code system ? Je ne trouve pas d'où vient le codeSystem actuellement implémenté. Il faudra alors trouver un autre code, le code OPTIN n'existe pas dans le JDV  https://hl7.org/fhir/R4/valueset-consent-policy.html
A noter que nous n'avons pas besoin de cette donnée, elle est imposer par FHIR

2024-01-15 12:08 UTC, nriss commented on input/FHIR/ESMSConsent.json
> +        "system": "http://terminology.hl7.org/5.0.0/CodeSystem/v3-ActCode",
Je ne comprends pas trop le problème, c'est pas le JDV bindé de base, c'est ça ? Peux tu me préciser le JDV et le binding strength associé ? Et quel code est-ce que vous auriez besoin ?

2024-01-15 15:27 UTC, nriss requested changes

2024-01-15 15:27 UTC, nriss commented on input/FHIR/StructureDefinition-esms-document-reference.json
> +        "id": "titreDocu",
Ne respecte pas le format id : https://hl7.org/fhir/elementdefinition.html#id

2024-01-15 15:28 UTC, nriss commented
Il y a des choses à corriger dans le Q/A : https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/ig/presta-98/qa.html
Mettre le package NOS dans les dépendances

2024-01-16 08:33 UTC, nriss commented on input/FHIR/ESMSConsent.json
> +        "system": "http://terminology.hl7.org/5.0.0/CodeSystem/v3-ActCode",
Le code "OPTIN" existe bien dans le CodeSystem http://terminology.hl7.org/CodeSystem/v3-ActCode en version 5.4.0 tel que défini dans les dépendances

<img width="918" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/a8af5367-cd2a-4b1b-ae36-fdb03357da44">

<img width="897" alt="image" src="https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/6b9212c4-0952-4e95-bcf3-2b2a5859b670">

https://terminology.hl7.org/5.4.0/CodeSystem-v3-ActCode.html

2024-01-17 08:05 UTC, nriss reviewed
C'est vraiment compliqué de review les json et les grosses PR comme ça
@SEBELIN est-il prévu de passer à FSH ?

2024-01-17 08:05 UTC, nriss commented on input/FHIR/SDOTask.json
> +      "valueIdentifier":{"value":"IdNat_Decision"}
Un identifier sans system ?

2024-01-17 08:05 UTC, nriss commented on input/FHIR/SDOTask.json
> +          "value": "IdNat_Decision"
idem

2024-01-17 08:05 UTC, nriss commented on input/FHIR/SDOTask.json
> +            "display": "idUnite"
Il y a juste un display ici ? Pas de JDV associé ?

2024-01-17 08:05 UTC, nriss commented on input/FHIR/SDOTask.json
> +              "display": "nomESMS"
idem

2024-01-17 08:14 UTC, jguihot commented
> C'est vraiment compliqué de review les json et les grosses PR comme ça @SEBELIN est-il prévu de passer à FSH ?
> 
> Côté Kereval, c'est une très mauvaise pratique de faire une PR de ce type, associée à une prestation :
> 
> * On ne sait pas ce qui est fait (aucune description, le titre n'est pas clair)
> * Très difficile à review
>   In fine, on obtient un guide qui n'est pas très qualitatif

@nriss , j'ai ouvert une issue pour le passage à FSH : [#67](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/issues/67). 
Nous n'avons jamais eu de prestation dédiée au passage en IG. L'IG a été créé principalement pour utiliser matchbox. Il reste un gros travail de mise en forme et mise à niveau pour en faire un support complet et facile à maintenir. Sujet partagé avec @SEBELIN .

Pour information, le titre correspond au nom de la prestation et du bon de commande ANS. Le besoin est donc borné par la propale.
Nous sommes encore en phase d'ajustement pour la gestion des PR. Je plussoie, il y a une marge d'amélioration

2024-01-19 17:30 UTC, jguihot requested changes
StructureDef à reprendre, OK pour le reste

2024-01-19 17:30 UTC, jguihot commented on input/pagecontent/contenu_dossier.md
description CDA ajoutée sur la page d'accueil (commit #90)
Section évaluation ajoutée et reformatée (commit #90)

2024-01-19 17:30 UTC, jguihot commented on input/pagecontent/contenu_dossier.md
bloc RelatedDocument ajouté
Nouvelle issue créée pour complétion avec spec CI-SIS

2024-01-19 17:30 UTC, jguihot commented on input/pagecontent/st_flux1.md
fix ajouté @KerJac35

2024-01-19 17:30 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +                    A noter que pour un cas nominal, la fr&eacute;quence de recherche est J-1. Pour un cas exceptionnel (premi&egrave;re connexion au SI-SDO d&rsquo;un DUI), la limite temporelle est
@KerJac35 , non traité

2024-01-19 17:30 UTC, jguihot commented on input/pagecontent/st_flux1.md
> +                    A noter que pour un cas nominal, la fr&eacute;quence de recherche est J-1. Pour un cas exceptionnel (premi&egrave;re connexion au SI-SDO d&rsquo;un DUI), la limite temporelle est
traité dans le commit #95

2024-01-19 17:37 UTC, nriss commented on input/FHIR/SDOTask.json
> +      "valueIdentifier":{"value":"IdNat_Decision"}
C'est plus propre d'avoir un system pour préciser quel type d'identifiant et enlever toute ambiguité effectivement. Peux-tu me rappeler de quel type d'identifiant il s'agit ?

2024-01-19 17:46 UTC, jguihot commented on input/FHIR/SDOTask.json
> +      "valueIdentifier":{"value":"IdNat_Decision"}
Il s'agit, dans ce cas précis d'un id identifiant au niveau national le dossier de décision d'orientation d'une personne orientée. Il est créé par ViaTrajectoire;
Nous avons également l'idDecision, qui lui correspond au numéro de dossier de décision au sein d'une MDPH. C'est la MDPH qui crée cet identifiant. 
Ces deux identifiants sont donc liés au document CDA

2024-01-24 07:33 UTC, jguihot commented
> C'est vraiment compliqué de review les json et les grosses PR comme ça @SEBELIN est-il prévu de passer à FSH ? Plus on fait le passage à FSH tard, plus ça sera coûteux
> 
> Côté Kereval, c'est une très mauvaise pratique de faire une PR de ce type, associée à une prestation :
> 
> * On ne sait pas ce qui est fait (aucune description, le titre n'est pas clair)
> * Très difficile à review
>   In fine, on obtient un guide qui n'est pas très qualitatif, les validations n'étant même pas faites : https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/pull/49/checks

@nriss , vu ensemble, les vérifications sont bien faites. Les warning restant ont trait à un dossier FSH non existant puisque nous n'avons pas de ressources au format FSH. Devrait être traité lors du passage en FSH => issue #67

2024-01-25 17:06 UTC, jguihot commented
> Il y a des choses à corriger dans le Q/A : https://ansforge.github.io/IG-fhir-medicosocial-suivi-decisions-orientation/ig/presta-98/qa.html Mettre le package NOS dans les dépendances

Tracé dans l'issue #100 et en partie traitée via les PR #80 , #94 et #87

2024-01-30 09:41 UTC, SEBELIN approved these changes
Validation sous réserve ajout historique + modification texte de description dans ressources de conformité pour la Task.

2024-01-30 09:46 UTC, nriss commented
Hello, merci pour la PR :)

Je vois encore deux choses à faire:
- Editer le message de la PR pour expliquer tous les travaux menés 
- Résoudre les conflits de la PR
![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/3fac65e3-7016-4517-b793-9c1a38d912f9)

2024-01-30 14:31 UTC, jguihot commented
Historique ajouté, conflit résolu, dernières corrections ajoutées et validées. OK pour merge @nriss si OK pour toi

2024-01-30 14:31 UTC, jguihot approved these changes
OK

2024-01-30 15:44 UTC, nriss approved these changes
Je fais confiance à @SEBELIN pour la review

2024-01-30 15:48 UTC, merged