Update narrative
ansforge/IG-fhir-medicosocial-suivi-decisions-orientation pull request #7
Opened 2023-08-30 14:43 UTC by TristanKEREVAL

2023-08-30 14:51 UTC, nriss requested changes

2023-08-30 14:51 UTC, nriss commented on sushi-config.yaml
> +    #specification_fonctionnelle.md:
Supprimer les parties commentées

2023-08-30 14:51 UTC, nriss commented on sushi-config.yaml
> +        title: Flux 5.1/5.2/5.3/5.4 - Recherche et consultation de statut
idem

2023-08-30 14:51 UTC, nriss commented on sushi-config.yaml
> +        Flux 1.1/1.2/1.3/1.4 - Recherche et consultation de personne orientee et decision: st_flux1.html
idem, et en-dessous

2023-08-30 14:56 UTC, nriss requested changes

2023-08-30 14:56 UTC, nriss commented on input/pagecontent/index.md
>  <p style="padding: 5px; border-radius: 5px; border: 2px solid maroon; background: #ffffe6; max-width: 790px">
Utiliser le style de GAP pour ne pas que la case déborde:
https://github.com/ansforge/IG-fhir-gestion-agenda-partage/blob/main/input/pagecontent/index.md?plain=1
https://ansforge.github.io/IG-fhir-gestion-agenda-partage/ig/main/

![image](https://github.com/ansforge/IG-fhir-medicosocial-suivi-decisions-orientation/assets/48218773/b4949716-30cd-45cf-aebb-823c73798942)

2023-08-30 15:17 UTC, nriss commented on input/pagecontent/st_flux1.4.md
> +En cas d’échec, le SI-SDO doit répondre avec le code HTTPS approprié tel que défini par l’API REST FHIR (Http - FHIR v4.3.0 (hl7.org)). Une ressource OperationOutcome doit également y être associé po
Pb version FHIR R4 ou R4b ? A voir sur l'ensemble du doc

2023-08-30 15:21 UTC, nriss requested changes

2023-08-30 15:21 UTC, nriss commented on input/pagecontent/st_flux5.2.md
> +-	Le statut « Période d’essai en cours » (code 185) ou « Usager pris en charge » (code 186) lié à un autre ESMS,
Respect consignes md (saut de ligne, *)

2023-08-30 15:21 UTC, nriss commented on sushi-config.yaml
> +        title: Autres ressources associées à la specification
spécification, il manque l'accent

2023-08-30 15:21 UTC, nriss commented on sushi-config.yaml
> +        Autres ressources: autres_ressources.html
Renommer differemment, autres ressources > autres ressources donne un path de navigation bizarre

2023-08-30 15:21 UTC, nriss commented on input/pagecontent/index.md
> +| **Primary Editor** | Prenom Nom | Agence du Numérique en Santé | <prenom.nom@address.email> |
A supprimer

2023-08-31 08:06 UTC, TristanKEREVAL commented on sushi-config.yaml
> +        Autres ressources: autres_ressources.html
Renommé en annexe

2023-09-01 12:08 UTC, nriss approved these changes

2023-09-05 14:15 UTC, merged